### ISSUE TITLE
Test if bind-mounted volumes can be used and PGDATA on Linux environment

### ISSUE THREAD

**Issue by yosukefk** [yosukefk/finn_preproc#15]
It has been difficult to use bind-mounted storage for PosrgreSQL database ($PGDATA directory), because windows filesystem doesnt support chown.  Want to know if it goes easy on Linux

**Comment by yosukefk** [comment]
@mbjoseph , could you test docker build and docker run, with bind mounted database?

Kartoza/postgis readme.md has a section for [Storing data on the host rather than the container](https://github.com/kartoza/docker-postgis#storing-data-on-the-host-rather-than-the-container).  Test if this works on Linux.  `-v $HOME/postgres_data:/var/lib/postgresql` is what I want to know if it works.   

If it's good, the log should look like

<pre>
$ docker logs finn_test_dbincontainer 2>&1 \| tail
/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/create_plpython3u.sql
Postgres initialisation process completed .... restarting in foreground
2019-01-09 22:17:57.284 UTC [206] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-01-09 22:17:57.284 UTC [206] LOG:  listening on IPv6 address "::", port 5432
2019-01-09 22:17:57.303 UTC [206] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-01-09 22:17:57.374 UTC [209] LOG:  database system was shut down at 2019-01-09 22:17:56 UTC
2019-01-09 22:17:57.395 UTC [206] LOG:  database system is ready to accept connections

</pre>

If not, log would look something like below, note **initdb: could not fsync file**


<pre>
$ docker logs finn_test_dbbindmount
Add rule to pg_hba: replication user
Setup master database
Creating Postgres data at /var/lib/postgresql/10/main
Initializing Postgres Database at /var/lib/postgresql/10/main
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/10/main ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
initdb: could not fsync file "/var/lib/postgresql/10/main/base/1": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/10/main/base/12991": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/10/main/base/12992": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/10/main/base": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/10/main/global": Invalid argument
initdb: could not fsync file "/var/lib/postgresql/10/main/pg_commit_ts": Invalid argument

... skipping...

psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
</pre>

**Comment by mbjoseph** [comment]
Sure - I'll test this out. Thanks for pinging me @yosukefk!

**Comment by mbjoseph** [comment]
Hi @yosukefk - just tested this out on Linux and it seems to be working. Here's what I did:

1. Build the container

`docker build -t finn .`

2. Run it, linking volumes as you described:

`docker run -v $HOME/postgres_data:/var/lib/postgresql --name 'finn' -p 5432:5432 -p 8888:8888 -d -e EARTHDATAUSER=... -e EARTHDATAPW='...' finn`

3. Then check logs with `docker logs finn` which prints: 

```
Add rule to pg_hba: replication user
Setup master database
Creating Postgres data at /var/lib/postgresql/10/main
Initializing Postgres Database at /var/lib/postgresql/10/main
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/10/main ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok

Success. You can now start the database server using:

    /usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main -l logfile start

Use modified postgresql.conf for greater speed (spatial and replication)
2019-01-10 15:58:50.290 UTC [44] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2019-01-10 15:58:50.293 UTC [44] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-01-10 15:58:50.307 UTC [49] LOG:  database system was shut down at 2019-01-10 15:58:50 UTC
2019-01-10 15:58:50.312 UTC [44] LOG:  database system is ready to accept connections
                             List of databases
   Name    |  Owner   | Encoding  | Collate | Ctype |   Access privileges   
-----------+----------+-----------+---------+-------+-----------------------
 postgres  | postgres | SQL_ASCII | C       | C     | 
 template0 | postgres | SQL_ASCII | C       | C     | =c/postgres          +
           |          |           |         |       | postgres=CTc/postgres
 template1 | postgres | SQL_ASCII | C       | C     | =c/postgres          +
           |          |           |         |       | postgres=CTc/postgres
(3 rows)

postgres ready
Postgis is missing, installing now
Creating template postgis
Enabling template_postgis as a template
UPDATE 1
Loading postgis extension
CREATE EXTENSION
Enabling hstore in the template
CREATE EXTENSION
Enabling topology in the template
CREATE EXTENSION
Loading legacy sql
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE OPERATOR CLASS
Setup postgres User:Password
CREATE ROLE
Check default db exists
Create default db gis
                                 List of databases
       Name       |  Owner   | Encoding  | Collate | Ctype |   Access privileges   
------------------+----------+-----------+---------+-------+-----------------------
 gis              | docker   | UTF8      | C       | C     | 
 postgres         | postgres | SQL_ASCII | C       | C     | 
 template0        | postgres | SQL_ASCII | C       | C     | =c/postgres          +
                  |          |           |         |       | postgres=CTc/postgres
 template1        | postgres | SQL_ASCII | C       | C     | =c/postgres          +
                  |          |           |         |       | postgres=CTc/postgres
 template_postgis | postgres | UTF8      | C       | C     | 
(5 rows)

2019-01-10 15:58:52.332 UTC [44] LOG:  received smart shutdown request
2019-01-10 15:58:52.335 UTC [44] LOG:  worker process: logical replication launcher (PID 55) exited with exit code 1
2019-01-10 15:58:52.337 UTC [50] LOG:  shutting down
2019-01-10 15:58:52.351 UTC [44] LOG:  database system is shut down

/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/create_plpython3u.sql


Postgres initialisation process completed .... restarting in foreground
2019-01-10 15:58:53.358 UTC [225] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-01-10 15:58:53.358 UTC [225] LOG:  listening on IPv6 address "::", port 5432
2019-01-10 15:58:53.361 UTC [225] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-01-10 15:58:53.374 UTC [228] LOG:  database system was shut down at 2019-01-10 15:58:52 UTC
2019-01-10 15:58:53.377 UTC [225] LOG:  database system is ready to accept connections

```

**Comment by yosukefk** [comment]
Oh great!!!    I am going to come up with issue #16, which I want to test if $HOME/postgres_data can be reused in postgresql in other images/containers.  I will send you another request to you.
