### ISSUE TITLE
Add more detail to README.md about NASA EarthData user name/password

### ISSUE THREAD

**Issue by mbjoseph** [yosukefk/finn_preproc#2]
We should explain in the README.md file what the EARTHDATAUSER and EARTHDATAPW are, and how to get an EarthData username and password, linking to this page: https://urs.earthdata.nasa.gov/

**Comment by yosukefk** [comment]
Actually, i'd get rid of this option, it doesnt have to be set when container got created.  I'd put this to jupyter notebook.

**Comment by mbjoseph** [comment]
Hey @yosukefk! Originally I had the same idea, but then realized that if the username and password are in the notebook, that would provide a security risk if the notebook exists on a public GitHub repository. So, providing them as environment variables in the call to `docker run` seemed less likely to cause users to expose their credentials. 

But, I'm open to other ways to pass in credentials!

**Comment by yosukefk** [comment]
I see, @mbjoseph , never thought about that.  We may want to keep the way you did.  We still need documentation of what is needed and why needed.

**Comment by yosukefk** [comment]
Done
