### ISSUE TITLE
Add instructions for using local active fire shapefiles

### ISSUE THREAD

**Issue by mbjoseph** [yosukefk/finn_preproc#25]
Eventually we need to add instructions for users to use active fire shapefiles that exist locally.

**Comment by mbjoseph** [comment]
Idea: we can consolidate all of the notebooks into one notebook, where we have a **configuration** code cell, which is the cell that users can edit to point to specific files.

**Comment by yosukefk** [comment]
In addition to the change suggested above, it should incorporate what USA test case was doing but in more straightforward way.  Code will check first if database has the necessary raster.  If not, behave like Oregon case, grab what needed and import.  It should purge the left over from previous import for the year, to make things simple.

**Comment by yosukefk** [comment]
pull request by @mbjoseph took care of this:  #34
