### ISSUE TITLE
Include Windows instructions for linking volumes in Docker

### ISSUE THREAD

**Issue by mbjoseph** [yosukefk/finn_preproc#3]
We should add instructions for Windows users to the README.md file about how to link volumes:

From Yo:

*...There are two changes needed to use in CMD.exe on windows.  $(pwd) needs to be changed to %cd% , ‘finn’, somehow CMD doesn’t like single quote.*

Also:

*​I need to go to “setting” of docker to allow access to C: drive (my only drive).  I didn’t do that, and the docker run command gives windows prompt if you want let this thing to access C: drive (something like that, couldn’t remember exactly).  I said yes,  but that was not enough.  So I believe this should be written down,  something like this https://stackoverflow.com/questions/33126271/how-to-use-volume-option-with-docker-toolbox-on-windows/39181789#39181789*

**Comment by yosukefk** [comment]
Spelling out //C/Users/yosuke/...  etc. would be more reliable, instead of using funky Windows style path...

**Comment by yosukefk** [comment]
README.md now has a way to do this on powershell.  pretty ugly but it works.

```powershell
# Function to convert windows path to what docker likes
filter docker-path {'/' + $_ -replace '\\', '/' -replace ':', ''}

# Create docker container and start
docker run --name finn -v ( (pwd | docker-path) + ':/home/finn')
```
