### ISSUE TITLE
instruction for git pull etc

### ISSUE THREAD

**Issue by yosukefk** [yosukefk/finn_preproc#35]
Need to also mention docker stop, maybe docker image rm needed, before docker build?

**Comment by yosukefk** [comment]
So like christine was ignoring message from docker run complaining that finn is already there .  We want instruction for "start over".  People may think that they wipe HDD and git pull then think that's it, but she actually have to worry about docker container/image to update things.

**Comment by yosukefk** [comment]
At the end of README there is instruction for docker stop, start etc.

We want to extend that:
- How to git pull to update the code
- Also, what if i want to "wipe everything and start over"

**Comment by mbjoseph** [comment]
Ok @yosukefk I can do this!

**Comment by yosukefk** [comment]
@mbjoseph seems like you have to be collaborator to be assigned.  Sent invitation.  

Obviously i am procrastinating now...

**Comment by yosukefk** [comment]
@mbjoseph , as i said in the mail, i want something stronger than `git pull`, which overwrites user's edit.  By design, regular users edit main_generic.ipynb, and that causes conflict when she wants to pull the newer files from repository.  Should I just instruct user to delete genaric.ipynb?    But there are cases like we delete files on repository.  This time i deleted testUSA etc.   then this causes another conflict.  Do we have to make user to manually delete files that conflicts with repository?

**Comment by yosukefk** [comment]
@mbjoseph says:

> Dealing with merge conflicts in git is a difficult problem. The simplest case arises when there are local changes that you do not need to keep, in which case you can undo the local changes, then pull:
> 
> ```
> git checkout -- .
> git pull
> ```
> 
> Otherwise, three is a real merge conflict and solving that is inherently difficult.
> 

I added this to README.md.  Hope this will do.
