### ISSUE TITLE
Modify wget scripts to work on Windows

### ISSUE THREAD

**Issue by mbjoseph** [yosukefk/finn_preproc#4]
From Yo: 

*​Somehow, the .sh scripts are changed to dos format in my local clone of the finn_preprocessor I got with GitHub desktop.  And in the script --password XXX was the last argument in the line.   So I believe that my password is appeneded with ‘\r’ and authentication was failing.  I had to test by “docker exec -it finn bash” to manually type the command, test with $EARTHDATAPW etc, and I think that’s the problem.  Easiest work around is to move the -P downloads to the end of line, guiding the password in the middle of line surrounded by whitespace.*

**Comment by yosukefk** [comment]
I created downloader.py which does the same thing as .sh file (downloadall() function).  I also added some more functions which checks the cksum values, identify tiles needed given set of points etc.  Still need to edit the notebook to use these.

**Comment by yosukefk** [comment]
Rewrote as a python module `downloeder.py`
