### ISSUE TITLE
Add start/stop instructions to README

### ISSUE THREAD

**Issue by mbjoseph** [yosukefk/finn_preproc#5]
We should add instructions for starting and stopping the container in the README:

​To stop the container, you can either to ^C from the terminal that is actively printing the output from the Jupyter notebook server, or from another terminal use:

```bash
docker stop finn
```

and then to start it again, you can use​:

```bash
docker start finn
```

​Then, once the container is running, you can start the notebook server via the same command that started it originally:

```bash
docker exec -it finn jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --notebook-dir /home/finn​
 ```

**Comment by yosukefk** [comment]
Done
