### ISSUE TITLE
Trouble installing docker image on Centos 7

### ISSUE THREAD

**Issue by dattilo** [yosukefk/finn_preproc#55]
Hi Yo,
   I can no longer build the finn docker as it fails with the following error:

Reading package lists...
W: Conflicting distribution: http://deb.debian.org/debian stable InRelease (expected stretch but got buster)
W: Conflicting distribution: http://deb.debian.org/debian stable-updates InRelease (expected stretch-updates but got buster-updates)
E: Could not open file /var/lib/apt/lists/deb.debian.org_debian_dists_stable-updates_main_binary-amd64_Packages.diff_Index - open (2: No such file or directory)
W: Conflicting distribution: http://security.debian.org/debian-security stable/updates InRelease (expected stretch but got buster)

**Comment by yosukefk** [comment]
Max, do you have Linux machine you can test this?  Otherwise I will work on this finding some appropriate linux box.

**Comment by yosukefk** [comment]
I reproduced @dattilo 's error,

<pre>
Step 3/15 : RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates     libglib2.0-0 libxext6 libsm6 libxrender1 postgresql-10-postgis-2.4 postgis git unzip
 ---> Running in 1a057ed8f33a
Get:1 http://deb.debian.org/debian stable InRelease [118 kB]
Get:2 http://security.debian.org/debian-security stable/updates InRelease [39.1 kB]
Get:3 http://deb.debian.org/debian stable-updates InRelease [49.3 kB]
Get:4 http://deb.debian.org/debian stable/main amd64 Packages [7897 kB]
Get:5 http://security.debian.org/debian-security stable/updates/main amd64 Packages [62.9 kB]
Get:6 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease [51.4 kB]
Get:7 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages [181 kB]
Get:8 http://deb.debian.org/debian stable-updates/main amd64 Packages.diff/Index [736 B]
Get:8 http://deb.debian.org/debian stable-updates/main amd64 Packages.diff/Index [736 B]
Get:9 http://deb.debian.org/debian stable-updates/main amd64 Packages [884 B]
Reading package lists...
W: Conflicting distribution: http://deb.debian.org/debian stable InRelease (expected stretch but got buster)
W: Conflicting distribution: http://security.debian.org/debian-security stable/updates InRelease (expected stretch but got buster)
W: Conflicting distribution: http://deb.debian.org/debian stable-updates InRelease (expected stretch-updates but got buster-updates)
E: Could not open file /var/lib/apt/lists/deb.debian.org_debian_dists_stable-updates_main_binary-amd64_Packages.diff_Index - open (2: No such file or directory)
The command '/bin/sh -c apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates     libglib2.0-0 libxext6 libsm6 libxrender1 postgresql-10-postgis-2.4 postgis git unzip' returned a non-zero code: 100
</pre>

I try this giant statement what it's doing if i can break them apart and sor out which one causing trouble.

**Comment by yosukefk** [comment]
This seems to have get the docker build to pass through the issue reported above,
https://github.com/romaricp/kit-starter-symfony-4-docker/issues/10

but doesn't go all the way.  Let me continue working on the Dockerfile, unless @mbjoseph comes to rescue.

**Comment by yosukefk** [comment]
With the above "fix", i cannot get postgresql-plpython3-10 to get installed...

<pre>
# apt-get install -y postgresql-plpython3-10
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 postgresql-plpython3-10 : Depends: libpython3.5 (>= 3.5.0~b1) but it is not installable
E: Unable to correct problems, you have held broken packages.
</pre>

**Comment by yosukefk** [comment]
#57 updates postgresql version from 10 to 11, and that should fix the problem.
